# Generated by Django 3.2 on 2021-04-18 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audiobook_ID', models.IntegerField(unique=True)),
                ('Name_of_the_audiobook', models.CharField(max_length=100)),
                ('Author_of_the_title', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('ADuration_in_number_of_seconds', models.PositiveIntegerField()),
                ('AUploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Podcast_ID', models.IntegerField(unique=True)),
                ('Name_of_the_podcast', models.CharField(max_length=100)),
                ('PDuration_in_number_of_seconds', models.PositiveIntegerField()),
                ('PUploaded_time', models.DateTimeField(auto_now_add=True)),
                ('Host', models.CharField(max_length=100)),
                ('Participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_ID', models.IntegerField(unique=True)),
                ('Name_of_the_song', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.PositiveIntegerField()),
                ('Uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
