# Generated by Django 3.2 on 2021-04-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='Audiobook_ID',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='Podcast_ID',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Song_ID',
        ),
    ]
